# Generated by Django 2.1.1 on 2018-10-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Landpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('title', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('vk', models.CharField(max_length=30)),
                ('fb', models.CharField(max_length=30)),
                ('copyrights', models.TextField()),
            ],
        ),
    ]
